#!/bin/sh
### BEGIN INIT INFO
# Provides:          ip46d
# Required-Start:    $network $local_fs
# Required-Stop:     $network $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: UDP IPv4 to IPv6
# Description:       Runs fio as a service to that fio clients can connect
#                    to it
### END INIT INFO

# Author: Xu Ruijun 1687701765@qq.com

EXECFILE=/home/xrj/program/internet/local_ddns/ip46.py
PIDFILE=/var/run/ip46d.pid

case "$1" in
    start)
        start-stop-daemon --start --pidfile $PIDFILE --make-pidfile \
                          --exec $EXECFILE --background
        ;;
    stop)
        start-stop-daemon --stop --pidfile $PIDFILE \
                          --retry 5
        rm -f $PIDFILE
        ;;
esac

exit 0
