#!/bin/sh
########################################################################
# Script of IPv6Net in `/etc/init.d`
# Copyright (C) 2022  Xu Ruijun | 1687701765@qq.com
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
########################################################################
#
### BEGIN INIT INFO
# Provides:          ip46d
# Required-Start:    $network $local_fs
# Required-Stop:     $network $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: UDP IPv4 to IPv6
# Description:       Runs fio as a service to that fio clients can connect
#                    to it
### END INIT INFO


EXECFILE=/home/xrj/program/internet/local_ddns/daemon.py
PIDFILE=/var/run/ipv6netd.pid

case "$1" in
    start)
        start-stop-daemon --start --pidfile $PIDFILE --make-pidfile \
                          --exec $EXECFILE --background
        ;;
    stop)
        start-stop-daemon --stop --pidfile $PIDFILE \
                          --retry 5
        rm -f $PIDFILE
        ;;
esac

exit 0
